name: Deploy to OCI

on:
  push:
    branches:
    - 'main'

jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: Deploy Repo
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_VM_HOST: ${{ secrets.OCI_VM_HOST }}
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@latest
        with:
          # hostname / IP of the server
          host: ${{ secrets.OCI_VM_HOST }}
          user: ${{ secrets.OCI_CLI_USER }}
          # private ssh key registered on the server
          private_key: ${{ secrets.OCI_KEY_CONTENT }}
          # command to be executed
          command: echo 'Host World'         
