name: Deploy to OCI

on:
  push:
    branches:
    - 'main'

jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: Deploy Repo
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_VM_HOST: ${{ secrets.OCI_VM_HOST }}
      OCI_VM_PRIVATE_KEY: ${{ secrets.OCI_VM_PRIVATE_KEY }}
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@latest
        with:
          # hostname / IP of the server
          host: ${{ secrets.OCI_VM_HOST }}
          user: ubuntu
          # private ssh key registered on the server
          private_key: ${{ secrets.OCI_VM_PRIVATE_KEY }}
          # command to be executed
          command: |
            rm -r /home/ubuntu/repo
            mkdir /home/ubuntu/repo
            git clone https://github.com/TinyAbra/ttrpg-website-deploy.git |
            cd /home/ubuntu/repo |
            npm install |
            npm run build
